/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by genmsg_cpp from file /home/team5/RSS-hydro/src/rss_msgs/msg/ArmMsg.msg
 *
 */


#ifndef RSS_MSGS_MESSAGE_ARMMSG_H
#define RSS_MSGS_MESSAGE_ARMMSG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rss_msgs
{
template <class ContainerAllocator>
struct ArmMsg_
{
  typedef ArmMsg_<ContainerAllocator> Type;

  ArmMsg_()
    : pwms()  {
      pwms.assign(0);
  }
  ArmMsg_(const ContainerAllocator& _alloc)
    : pwms()  {
      pwms.assign(0);
  }



   typedef boost::array<int32_t, 8>  _pwms_type;
  _pwms_type pwms;




  typedef boost::shared_ptr< ::rss_msgs::ArmMsg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rss_msgs::ArmMsg_<ContainerAllocator> const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;

}; // struct ArmMsg_

typedef ::rss_msgs::ArmMsg_<std::allocator<void> > ArmMsg;

typedef boost::shared_ptr< ::rss_msgs::ArmMsg > ArmMsgPtr;
typedef boost::shared_ptr< ::rss_msgs::ArmMsg const> ArmMsgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rss_msgs::ArmMsg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rss_msgs::ArmMsg_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace rss_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'rss_msgs': ['/home/team5/RSS-hydro/src/rss_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::rss_msgs::ArmMsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rss_msgs::ArmMsg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rss_msgs::ArmMsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rss_msgs::ArmMsg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rss_msgs::ArmMsg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rss_msgs::ArmMsg_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rss_msgs::ArmMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4c5412bbb934bf99b5395848aebdddf2";
  }

  static const char* value(const ::rss_msgs::ArmMsg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4c5412bbb934bf99ULL;
  static const uint64_t static_value2 = 0xb5395848aebdddf2ULL;
};

template<class ContainerAllocator>
struct DataType< ::rss_msgs::ArmMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rss_msgs/ArmMsg";
  }

  static const char* value(const ::rss_msgs::ArmMsg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rss_msgs::ArmMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32[8] pwms\n\
";
  }

  static const char* value(const ::rss_msgs::ArmMsg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rss_msgs::ArmMsg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.pwms);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct ArmMsg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rss_msgs::ArmMsg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rss_msgs::ArmMsg_<ContainerAllocator>& v)
  {
    s << indent << "pwms[]" << std::endl;
    for (size_t i = 0; i < v.pwms.size(); ++i)
    {
      s << indent << "  pwms[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.pwms[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // RSS_MSGS_MESSAGE_ARMMSG_H
