/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by genmsg_cpp from file /home/team5/RSS-hydro/src/rss_msgs/msg/BlobMsg.msg
 *
 */


#ifndef RSS_MSGS_MESSAGE_BLOBMSG_H
#define RSS_MSGS_MESSAGE_BLOBMSG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rss_msgs
{
template <class ContainerAllocator>
struct BlobMsg_
{
  typedef BlobMsg_<ContainerAllocator> Type;

  BlobMsg_()
    : centroidX(0.0)
    , centroidY(0.0)
    , targetArea(0.0)
    , targetRange(0.0)
    , targetBearing(0.0)  {
    }
  BlobMsg_(const ContainerAllocator& _alloc)
    : centroidX(0.0)
    , centroidY(0.0)
    , targetArea(0.0)
    , targetRange(0.0)
    , targetBearing(0.0)  {
    }



   typedef float _centroidX_type;
  _centroidX_type centroidX;

   typedef float _centroidY_type;
  _centroidY_type centroidY;

   typedef float _targetArea_type;
  _targetArea_type targetArea;

   typedef float _targetRange_type;
  _targetRange_type targetRange;

   typedef float _targetBearing_type;
  _targetBearing_type targetBearing;




  typedef boost::shared_ptr< ::rss_msgs::BlobMsg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rss_msgs::BlobMsg_<ContainerAllocator> const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;

}; // struct BlobMsg_

typedef ::rss_msgs::BlobMsg_<std::allocator<void> > BlobMsg;

typedef boost::shared_ptr< ::rss_msgs::BlobMsg > BlobMsgPtr;
typedef boost::shared_ptr< ::rss_msgs::BlobMsg const> BlobMsgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rss_msgs::BlobMsg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rss_msgs::BlobMsg_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace rss_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'rss_msgs': ['/home/team5/RSS-hydro/src/rss_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::rss_msgs::BlobMsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rss_msgs::BlobMsg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rss_msgs::BlobMsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rss_msgs::BlobMsg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rss_msgs::BlobMsg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rss_msgs::BlobMsg_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rss_msgs::BlobMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "be4448f231e0d35f6995beab99ac5278";
  }

  static const char* value(const ::rss_msgs::BlobMsg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xbe4448f231e0d35fULL;
  static const uint64_t static_value2 = 0x6995beab99ac5278ULL;
};

template<class ContainerAllocator>
struct DataType< ::rss_msgs::BlobMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rss_msgs/BlobMsg";
  }

  static const char* value(const ::rss_msgs::BlobMsg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rss_msgs::BlobMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 centroidX\n\
float32 centroidY\n\
float32 targetArea\n\
float32 targetRange\n\
float32 targetBearing\n\
";
  }

  static const char* value(const ::rss_msgs::BlobMsg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rss_msgs::BlobMsg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.centroidX);
      stream.next(m.centroidY);
      stream.next(m.targetArea);
      stream.next(m.targetRange);
      stream.next(m.targetBearing);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct BlobMsg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rss_msgs::BlobMsg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rss_msgs::BlobMsg_<ContainerAllocator>& v)
  {
    s << indent << "centroidX: ";
    Printer<float>::stream(s, indent + "  ", v.centroidX);
    s << indent << "centroidY: ";
    Printer<float>::stream(s, indent + "  ", v.centroidY);
    s << indent << "targetArea: ";
    Printer<float>::stream(s, indent + "  ", v.targetArea);
    s << indent << "targetRange: ";
    Printer<float>::stream(s, indent + "  ", v.targetRange);
    s << indent << "targetBearing: ";
    Printer<float>::stream(s, indent + "  ", v.targetBearing);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RSS_MSGS_MESSAGE_BLOBMSG_H
