"""autogenerated by genpy from rss_msgs/BlobMsg.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class BlobMsg(genpy.Message):
  _md5sum = "be4448f231e0d35f6995beab99ac5278"
  _type = "rss_msgs/BlobMsg"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """float32 centroidX
float32 centroidY
float32 targetArea
float32 targetRange
float32 targetBearing

"""
  __slots__ = ['centroidX','centroidY','targetArea','targetRange','targetBearing']
  _slot_types = ['float32','float32','float32','float32','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       centroidX,centroidY,targetArea,targetRange,targetBearing

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(BlobMsg, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.centroidX is None:
        self.centroidX = 0.
      if self.centroidY is None:
        self.centroidY = 0.
      if self.targetArea is None:
        self.targetArea = 0.
      if self.targetRange is None:
        self.targetRange = 0.
      if self.targetBearing is None:
        self.targetBearing = 0.
    else:
      self.centroidX = 0.
      self.centroidY = 0.
      self.targetArea = 0.
      self.targetRange = 0.
      self.targetBearing = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_5f.pack(_x.centroidX, _x.centroidY, _x.targetArea, _x.targetRange, _x.targetBearing))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(_x))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(_x))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 20
      (_x.centroidX, _x.centroidY, _x.targetArea, _x.targetRange, _x.targetBearing,) = _struct_5f.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_5f.pack(_x.centroidX, _x.centroidY, _x.targetArea, _x.targetRange, _x.targetBearing))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(_x))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(_x))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 20
      (_x.centroidX, _x.centroidY, _x.targetArea, _x.targetRange, _x.targetBearing,) = _struct_5f.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_5f = struct.Struct("<5f")
